name: deploy-app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Adding Known Host
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Hammad Website
        uses: shimataro/ssh-key-action@v2
        with:
          host: 143.244.131.229
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.root }}@${{ secrets.SSH_HOST }}:~/
