name: deploy-app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-hammad-app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: mkdir hammad-portfolio && cd hammad-portfolio && git clone git@github.com:umerkang66/hammad-portfolio.git && echo 'Deployment successful to digital ocean' && pm2 delete 0 && cd hammad-portfolio && pm2 start npm -- start
