name: deploy-app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-nodejs-app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 143.244.131.229
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          username: root

          script: git clone git@github.com:umerkang66/hammad-portfolio.git && pm2 delete 0 && cd hammad-portfolio && npm run build && pm2 start npm -- start
