name: Deploy Hammad Website
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            pm2 delete 0
            cd hammad-portfolio
            git pull origin master
            yarn install
            yarn build
            pm2 start yarn -- start
