name: deploy-app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # This will create a directory named `my-repo` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: my-repo
      # Runs a set of commands using the runners shell
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: my-repo
          remote: ~/hammad-portfolio
          host: 143.244.131.229
          port: 59666
          username: root
          privateKey: ${{secrets.SSH_KEY}}
